# Generated by Django 2.2.16 on 2022-09-16 16:56

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[recipes.validators.validate_cooking_time], verbose_name='Время приготовления'),
        ),
    ]
