# Generated by Django 2.2.16 on 2022-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220907_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(choices=[('breakfast', 'Завтрак'), ('dinner', 'Обед'), ('supper', 'Ужин')], related_name='recipes', to='recipes.Tag', verbose_name='Ярлык'),
        ),
    ]
