# Generated by Django 2.2.16 on 2022-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220910_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='the_recipe', through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
    ]
